### ISSUE TITLE
PDF-Vorschau ist nicht möglich

### ISSUE THREAD

**Issue by xolf** [homeworker-app/desktop#10]
In der App können `object`-Tags anscheinend nicht verwendet werden. Deswegen ist keine Vorschau von PDF-Dokumenten möglich.

![Bildschirmfoto 2020-08-26 um 00 25 27](https://user-images.githubusercontent.com/8250052/91233993-b2101180-e732-11ea-9d08-398ccd299692.png)

**Comment by rasmuslos** [comment]
https://github.com/homeworker-app/desktop/commit/905fdef31e0ef48e33fc58b10ebdd5415df153a9
