### ISSUE TITLE
Updater hinzufügen

### ISSUE THREAD

**Issue by rasmuslos** [homeworker-app/desktop#11]
Aktuell werden keine Updates gemacht. Es muss noch der Updater von electron builder hinzugefügt werden

**Comment by xolf** [comment]
@rasmuslos wieviel Aufwand ist es denn Updater noch zu implementieren?

**Comment by rasmuslos** [comment]
Von der Electron-Builder Seite:
```
Quick Setup Guide

Install electron-updater as an app dependency.
Configure publish.
Use autoUpdater from electron-updater instead of electron:
Call autoUpdater.checkForUpdatesAndNotify()
```

**Comment by rasmuslos** [comment]
> Von der Electron-Builder Seite:
> 
> ```
> Quick Setup Guide
> 
> Install electron-updater as an app dependency.
> Configure publish.
> Use autoUpdater from electron-updater instead of electron:
> Call autoUpdater.checkForUpdatesAndNotify()
> ```

https://www.electron.build/auto-update

**Comment by xolf** [comment]
@rasmuslos kannst du das integrieren?

Der Updater ist inzwischen so weit eingerichtet, dass er danach automatisch die App veröffentlichen kann.
