### ISSUE TITLE
Nur redirect.homeworker.li Links im Browser öffnen

### ISSUE THREAD

**Issue by xolf** [homeworker-app/desktop#16]
Die native App soll nur noch Links, welche über `redirect.homeworker.li` gehgen im externen Browser anzeigen.

Alle anderen Links sollen in der Nativen app geöffnet werden. Das gilt als Vorbereitung auf #8.

**Comment by rasmuslos** [comment]
Leider führt das zu Fehlern mit z.B. den Bildern in den Chats. Man müsste diese über `redirect.homeworker.li` anzeigen oder eine White- bzw. Blacklist machen
