### ISSUE TITLE
Screen Sharing geht nicht in BBB

### ISSUE THREAD

**Issue by xolf** [homeworker-app/desktop#36]

**Comment by rasmuslos** [comment]
Das ist ein Fehler mit der plist schaue ich mit an

**Comment by rasmuslos** [comment]
https://github.com/hokein/electron-sample-apps/tree/master/desktop-capture / https://github.com/fireship-io/223-electron-screen-recorder

**Comment by xolf** [comment]
Was bedeuted das für uns?

**Comment by rasmuslos** [comment]
Gute Frage, ich schaue mal ob sich das implementieren lässt

**Comment by xolf** [comment]
@rasmuslos konntest du schon Erkentnisse erhalten?

**Comment by rasmuslos** [comment]
Wenn ich das richtig verstanden habe muss das in der runtime implementiert werden. Wahrscheinlich überschreibe ich die `getMediaDevices` Methode mit einer eigenen

**Comment by rasmuslos** [comment]
https://github.com/hokein/electron-sample-apps/blob/master/desktop-capture/app.js

**Comment by rasmuslos** [comment]
Fixed in #52
