### ISSUE TITLE
Icons der Push-Nachrichten anzeigen

### ISSUE THREAD

**Issue by xolf** [homeworker-app/desktop#39]
Bisher werden keine Icons in den Push-Nachrichten angezeigt. Da aber in Zukunft bei den Push-Nachrichten die Profilbilder mit gesendet werden sind die Icons wieder von Bedeutung und werden standardmäßig nicht mit dem Homeworker-Logo befüllt. Somit ist https://github.com/homeworker-app/desktop/issues/9 obsolet.

**Comment by rasmuslos** [comment]
Fixed in #40
