### ISSUE TITLE
Running Homeworker.li on Raspberry Pi

### ISSUE THREAD

**Issue by p3ling** [homeworker-app/desktop#54]
Dear all,

after a mail exchange Mr. Theimer asked me to highlight the following issue/change request:

The AppImage for Linux systems does not include an image/build script for ARM platforms of Raspberry Pi.
Could you please release an update that makes Homeworker run on the new Pi 4?

I can help test the image, if need be.

Thanks in advance,
Philippe

**Comment by rasmuslos** [comment]
I will look at this

**Comment by rasmuslos** [comment]
That would be a Debian package, right?

**Comment by p3ling** [comment]
Hi,

Thanks  for checking back, Rasbian is the system based on Debian. More importantly though it needs to be built for ARM processor.

Regards
Philippe

Von meinem iPhone gesendet

**Comment by p3ling** [comment]
Hallo,
 falls es hilft, von unserem aktuellen Raspberry 4 : 

cat /proc/cpuinfo 
processor	: 0
model name	: ARMv7 Processor rev 3 (v7l)
BogoMIPS	: 108.00
Features	: half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm crc32 
CPU implementer	: 0x41
CPU architecture: 7
CPU variant	: 0x0
CPU part	: 0xd08
CPU revision	: 3

processor	: 1
model name	: ARMv7 Processor rev 3 (v7l)
BogoMIPS	: 108.00
Features	: half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm crc32 
CPU implementer	: 0x41
CPU architecture: 7
CPU variant	: 0x0
CPU part	: 0xd08
CPU revision	: 3

processor	: 2
model name	: ARMv7 Processor rev 3 (v7l)
BogoMIPS	: 108.00
Features	: half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm crc32 
CPU implementer	: 0x41
CPU architecture: 7
CPU variant	: 0x0
CPU part	: 0xd08
CPU revision	: 3

processor	: 3
model name	: ARMv7 Processor rev 3 (v7l)
BogoMIPS	: 108.00
Features	: half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm crc32 
CPU implementer	: 0x41
CPU architecture: 7
CPU variant	: 0x0
CPU part	: 0xd08
CPU revision	: 3

Hardware	: BCM2711
Revision	: c03112
Serial		: 10000000d23503c7
Model		: Raspberry Pi 4 Model B Rev 1.2

---------------------------------------

Im Vergleich ein älterer Raspberry 3:

cat /proc/cpuinfo 
processor	: 0
model name	: ARMv7 Processor rev 4 (v7l)
BogoMIPS	: 76.80
Features	: half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm crc32 
CPU implementer	: 0x41
CPU architecture: 7
CPU variant	: 0x0
CPU part	: 0xd03
CPU revision	: 4

processor	: 1
model name	: ARMv7 Processor rev 4 (v7l)
BogoMIPS	: 76.80
Features	: half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm crc32 
CPU implementer	: 0x41
CPU architecture: 7
CPU variant	: 0x0
CPU part	: 0xd03
CPU revision	: 4

processor	: 2
model name	: ARMv7 Processor rev 4 (v7l)
BogoMIPS	: 76.80
Features	: half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm crc32 
CPU implementer	: 0x41
CPU architecture: 7
CPU variant	: 0x0
CPU part	: 0xd03
CPU revision	: 4

processor	: 3
model name	: ARMv7 Processor rev 4 (v7l)
BogoMIPS	: 76.80
Features	: half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm crc32 
CPU implementer	: 0x41
CPU architecture: 7
CPU variant	: 0x0
CPU part	: 0xd03
CPU revision	: 4

Hardware	: BCM2835
Revision	: a02082
Serial	: 00000000f2a6439b
Model	: Raspberry Pi 3 Model B Rev 1.2

**Comment by p3ling** [comment]
und das aktuelle image cat /proc/etc/os-release

PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"

**Comment by rasmuslos** [comment]
Ich schau mir das mal an. Allerdings arbeite ich aktuell mehr am Chat als an der Desktop app, das heißt wenn kommt das leider erst in ein paar Wochen. Zudem unterstützt `electron-builder` nur bedingt arm builds. Ich schau mir das aber auf jeden fall mal an

**Comment by p3ling** [comment]
Hi,
Chat klingt wichtiger, ich verstehe die Priorität. Aktuell hat meine Tochter mit einigen Problemen in. Homeworker zu kämpfen.
Am nervigsten momentan: Unmute funktioniert nicht in der Videokonferenz auf IPAD.

Bzgl pi Build habe ich kurz recherchiert, um Euch Zeit zu sparen:
AppImage scheint wohl einfacher zu sein als DEB package und funktioniert auch auf Rapbian.
Ihr benötigt wohl die Hardware = Pi 4, habt Ihr einen?

Diese drei Links zeigen Fixes zu den häufigsten Schwierigkeiten und Lösungen:

https://www.beekeeperstudio.io/blog/electron-apps-for-arm-and-raspberry-pi <https://www.beekeeperstudio.io/blog/electron-apps-for-arm-and-raspberry-pi>

https://stackoverflow.com/questions/57813389/how-do-i-build-and-install-an-electron-app-for-raspbian-using-appimage <https://stackoverflow.com/questions/57813389/how-do-i-build-and-install-an-electron-app-for-raspbian-using-appimage>

https://github.com/electron-userland/electron-builder-binaries/issues/20 <https://github.com/electron-userland/electron-builder-binaries/issues/20> 

mksquashfs.zip <https://github.com/electron-userland/electron-builder-binaries/files/3371160/mksquashfs.zip>  nutzen wg glibc bug s. GitHub Link für Erklärungen

Target armv7l

Wie kann ich noch helfen? 
Bin zwar als Coder etwas eingerostet, aber wenn ich von Euch ein „HelloWorld“ Skelett mit den notwendigen Libraries bekomme, kann ich versuchen auf dem Pi zu kompilieren.

Gruß,
Philippe Dreiling

**Comment by rasmuslos** [comment]
> Am nervigsten momentan: Unmute funktioniert nicht in der Videokonferenz auf IPAD

Homeworker nutzt Jitzi Meet bzw. Big Blue Button, du musst bei den Entsprechenden Anbietern nach Hilfe suchen. Hilfe zu Big Blue Button gibt es auch im Homeworker Support.

Der [Stack-Overflow](https://stackoverflow.com/questions/57813389/how-do-i-build-and-install-an-electron-app-for-raspbian-using-appimage) Link sieht vielversprechend aus, das könnte Funktionieren. Die App wird auf GitHub-Actions gebaut, an sich gibt es keinen Raspberry Pi, allerdings kann man Worker selber hosten.

Ansonsten wird eigentlich keine Hilfe gebraucht, die App funktionier prinzipiell auf auf arm-Geräten, es müssen nur builds erstellt werden, im besten Fall mit Electron-Builder, das ist die Hürde

**Comment by rasmuslos** [comment]
Durch das hinzufügen von
```json
{
  "target": "AppImage",
  "arch": [
    "x64",
    "arm64",
    "armv7l"
  ]
}
```
unter den `targets` bei `linux` kannst du dir ein RaspberryPi-AppImage erstellen. Da GitHub Aktions aktuell keine `armv7l` Runner hat kann das allerdings nicht automatisch erstellt werden. Auf deinem Raspberry PI kannst du allerdings durch `git clone https://github.com/homeworker-app/desktop.git && cd homeworker-desktop && npm i` die app aufsetzten, die `package.json` durch
```json
{
  "name": "homeworker-desktop",
  "maintainers": [
    "support@homeworker.li"
  ],
  "productName": "Homeworker",
  "version": "1.1.19",
  "description": "Desktop app for Windows and MacOS",
  "main": "src/main.js",
  "scripts": {
    "start": "electron .",
    "start:dev": "START_URL=http://localhost:8080 electron .",
    "dist": "electron-builder",
    "lint": "npx eslint ./src/"
  },
  "repository": {
    "type": "git",
    "url": "https://github.com/homeworker-app/desktop.git"
  },
  "author": {
    "name": "Rasmus Krämer",
    "url": "https://rfk.io",
    "email": "support@homeworker.li"
  },
  "license": "ISC",
  "devDependencies": {
    "electron": "9.4.4",
    "electron-builder": "^22.8.0",
    "electron-builder-notarize": "^1.2.0",
    "eslint": "^7.8.1",
    "eslint-plugin-import": "^2.22.0"
  },
  "dependencies": {
    "electron-updater": "^4.3.4",
    "update-electron-app": "^1.5.0"
  },
  "build": {
    "appId": "info.xolf.homeworker",
    "productName": "Homeworker",
    "copyright": "Copyright © 2021 Homeworker GmbH",
    "compression": "normal",
    "asar": true,
    "extends": null,
    "afterSign": "electron-builder-notarize",
    "linux": {
      "target": [
        {
          "target": "AppImage",
          "arch": [
            "x64",
            "arm64",
            "armv7l"
          ]
        },
        "deb",
        "snap"
      ]
    },
    "win": {
      "target": [
        {
          "target": "nsis",
          "arch": [
            "x64",
            "ia32"
          ]
        },
        "portable",
        "appx"
      ]
    },
    "mac": {
      "entitlements": "build/entitlements.mac.plist",
      "entitlementsInherit": "build/entitlements.mac.plist",
      "category": "public.app-category.education",
      "hardenedRuntime": true,
      "extendInfo": {
        "NSCameraUsageDescription": "Die kamera wird ausschließlich verwendet um am Videoanrufen teilzunehmen",
        "NSMicrophoneUsageDescription": "Das Mikrofon wird ausschließlich verwendet um am Anrufen teilzunehmen"
      },
      "target": [
        "dmg",
        "zip"
      ],
      "electronLanguages": [
        "de",
        "de_DE"
      ]
    },
    "appx": {
      "applicationId": "info.xolf.homeworker",
      "displayName": "Homeworker"
    },
    "mas": {
      "entitlements": "build/entitlements.mac.plist",
      "entitlementsInherit": "build/entitlements.mac.plist",
      "hardenedRuntime": false
    }
  }
}
```
ersetzten und `npm run build` ausführen. Dadurch solltest du im Ordner `dist` ein `armv7l` AppImage bekommen

**Comment by p3ling** [comment]
Cool, danke, probiere ich aus, komme vielleicht erst am Wochenende dazu.
