### ISSUE TITLE
Appimage icons

### ISSUE THREAD

**Issue by rasmuslos** [homeworker-app/desktop#56]
Icons für Linux app hinzufügen

**Comment by rasmuslos** [comment]
https://www.electron.build/configuration/linux

**Comment by rasmuslos** [comment]
Eigentlich sollte das MacOS icon verwendet werden

**Comment by eladyn** [comment]
Leider existiert dieses Problem auch noch in der neuesten Version.

Das generierte AppImage enthält die folgende Ordnerstruktur:
```
.DirIcon
AppRun
LICENSE.electron.txt
LICENSES.chromium.html
chrome-sandbox
chrome_100_percent.pak
chrome_200_percent.pak
homeworker-desktop
homeworker-desktop.desktop
homeworker-desktop.png
icudtl.dat
libEGL.so
libGLESv2.so
libffmpeg.so
libvk_swiftshader.so
libvulkan.so
locales
locales/am.pak
...
locales/zh-TW.pak
resources
resources/app-update.yml
resources/app.asar
resources.pak
snapshot_blob.bin
swiftshader
swiftshader/libEGL.so
swiftshader/libGLESv2.so
usr
usr/lib
usr/lib/libXss.so.1
usr/lib/libXtst.so.6
usr/lib/libappindicator.so.1
usr/lib/libgconf-2.so.4
usr/lib/libindicator.so.7
usr/lib/libnotify.so.4
usr/share
usr/share/icons
usr/share/icons/hicolor
usr/share/icons/hicolor/0x0
usr/share/icons/hicolor/0x0/apps
usr/share/icons/hicolor/0x0/apps/homeworker-desktop.png
v8_context_snapshot.bin
vk_swiftshader_icd.json
```

D.h., das Icon wird immernoch in `0x0` gepackt und nach extrahieren oder mounten kann man auch sehen, dass `homeworker-desktop.png` 288x288 groß ist.

Ein Grund hierfür könnte sein, dass electron-builder `icon.png` höher priorisiert als `icon.icns`. Inwiefern werden die anderen beiden Dateien (`icon.png` und `icon.ico`) überhaupt noch benötigt? Wenn ich das richtig verstanden habe in dem oben verlinkten Artikel, kann `icon.icns` verwendet werden, um alle nötigen Icons zu generieren, oder?
