### ISSUE TITLE
Unterstützung für 32-Bit Windows

### ISSUE THREAD

**Issue by xolf** [homeworker-app/desktop#57]
Bisher unterstützen wir noch kein 32-Bit Windows. Da in einigen Schulnetzwerken und auch privat Haushalten diese Version noch verwendet wird, wäre es stark hilfreich diese auch zu unterstützen.

**Comment by rasmuslos** [comment]
https://github.com/electron-userland/electron-builder/issues/1897#issuecomment-320454346
