### ISSUE TITLE
Doppeltes Bild aus der Push-Nachricht

### ISSUE THREAD

**Issue by xolf** [homeworker-app/desktop#9]
Bei den Push-Nachrichten werden unter MacOS das Homeworker-Logo doppelt angezeigt. Einmal das App Icon und das Bild der Push-Nachricht selber, welches angehangen wird, damit bei den Benachrichtigungen der Browser auch das Homeworker Logo erscheint.

Entweder entfernt man nur das Bild, wenn es das Homeworker-Logo ist, oder man ignoriert alle Bilder aus den Push-Nachrichten.

**Comment by rasmuslos** [comment]
Das eine ist das App Icon, das andere ist das Bild, man müsste alle Bilder ignorieren
